# Workflow Name
name : First Workflow
# Trigger
on : 
  push :
  workflow_dispatch:
 
jobs:
#First job
  Hello-job:
     # runner - Github hosted
     runs-on : ubuntu-latest
     steps:
       - name : Hello World
         run : echo "Hello World"
         
#Second job
echo-goodbye:
needs: Hello-job
runs-on : ubuntu-slim
steps:
       - name : Say Goodbye
         run : echo "Good bye"
         #Multiple commands
       - name : Multi-line bash
         run : |
         echo "I am"
         echo "Multi-line"
         echo "script"
         

